services:
  event-reminder-server-db-dev:
    image: postgres:latest
    container_name: event-reminder-server-db-dev
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=event_reminder
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - event-reminder-network-dev
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
  event-reminder-server-migrate-dev:
    image: event-reminder-server-migrate-dev:latest
    container_name: event-reminder-server-migrate-dev
    build:
      context: ../../event-reminder
      dockerfile: ./docker/Dockerfile
      target: migrate
    depends_on:
      - event-reminder-server-db-dev
    entrypoint: >
      sh -c "cd /src &&
        dotnet build EventReminder.sln &&
        dotnet ef database update --project EventReminder.Migrations/EventReminder.Migrations.csproj --startup-project EventReminder/EventReminder.csproj"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=event-reminder-server-db-dev;Database=event_reminder;Username=postgres;Password=postgres
    networks:
      - event-reminder-network-dev
    
  oauth2-proxy-dev:
    container_name: oauth2-proxy-dev
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - "4180:4180"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - event-reminder-network-dev
    environment:
      - OAUTH2_PROXY_PROVIDER=github
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_REDIRECT_URL=${OAUTH2_PROXY_REDIRECT_URL}
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_UPSTREAMS=${SVELTEKIT_SERVER_URL},${DOTNET_SERVER_URL}/api/
      - OAUTH2_PROXY_HTTP_ADDRESS=http://0.0.0.0:4180
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_WHITELIST_DOMAINS=${SVELTEKIT_SERVER_DOMAIN},${DOTNET_SERVER_DOMAIN}
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true

volumes:
  db-data:

networks:
  event-reminder-network-dev:
    driver: bridge