services:
  zerotier-container:
    image: zerotier-container
    build:
      context: ./zerotier
      dockerfile: ./Dockerfile
    networks:
      - event-reminder-network
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    restart: unless-stopped
  event-reminder-server:
    build:
      context: ../event-reminder
      dockerfile: ./docker/Dockerfile
    networks:
      - event-reminder-network
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      - SIGNAL_REST_CLI_URL=${SIGNAL_REST_CLI_URL}
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
  event-reminder-client:
    build:
      context: ../event-reminder-client
      dockerfile: ./docker/Dockerfile
    networks:
      - event-reminder-network
    environment:
      - NODE_ENV=production
      - FE_DEVELOPMENT=${FE_DEVELOPMENT}
      - DOTNET_SERVER_URL=${DOTNET_SERVER_URL}
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - "4180:4180"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - event-reminder-client
    networks:
      - event-reminder-network
    environment:
      - OAUTH2_PROXY_PROVIDER=github
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_REDIRECT_URL=${OAUTH2_PROXY_REDIRECT_URL}
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_UPSTREAMS=${SVELTEKIT_SERVER_URL},${DOTNET_SERVER_URL}/api/
      - OAUTH2_PROXY_HTTP_ADDRESS=http://0.0.0.0:4180
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_WHITELIST_DOMAINS=${SVELTEKIT_SERVER_DOMAIN},${DOTNET_SERVER_DOMAIN}
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true

volumes:
  db-data:

networks:
  event-reminder-network:
    driver: bridge